### ISSUE TITLE
Immediate segfault on OSX, works anyway?

### ISSUE THREAD

**Issue by randyzwitch** [aviks/JavaCall.jl#17]
What do you think about this behavior? I have Java installed via Homebrew on OSX

```julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.3.10 (2015-06-24 13:54 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

julia> using JavaCall
Loaded /Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre/lib/server/libjvm.dylib

julia> JavaCall.init(["-Xmx128M"])

signal (11): Segmentation fault: 11
unknown function (ip: 318931636)

julia> jlm = @jimport java.lang.Math
JavaObject{symbol("java.lang.Math")} (constructor with 2 methods)

julia> jcall(jlm, "sin", jdouble, (jdouble,), pi/2)
1.0

julia> jnu = @jimport java.net.URL
JavaObject{symbol("java.net.URL")} (constructor with 2 methods)

julia> gurl = jnu((JString,), "http://www.google.com")
JavaObject{symbol("java.net.URL")}(Ptr{Void} @0x00007f7ffc199d08)

julia> jcall(gurl, "getHost", JString,())
"www.google.com"

julia> j_u_arrays = @jimport java.util.Arrays
JavaObject{symbol("java.util.Arrays")} (constructor with 2 methods)

julia> jcall(j_u_arrays, "binarySearch", jint, (Array{jint,1}, jint), [10,20,30,40,50,60], 40)
3
```

**Comment by aviks** [comment]
Yes. The JVM uses segfaults to signal null values at some point, and then catches and handles them. Julia also installs a signal handler, which prints out the message you see. However since the JVM ultimately catches the signal, the program carries on nevertheless. So while the segfault message is scary, it is harmless. 

If you do get a legitimate segfault, Julia will exit after printing its C stack. That would be a bug in JavaCall, and should be fixed. 

This message can be suppressed in 0.4 by starting `julia` with the `--handle-signal=no` command line flag.  I should probably put this in a FAQ somewhere.

**Comment by waTeim** [comment]
You know I'm not convinced this is not an error, but rather it's just a error that the JVM has a way to correct after it happens.  If so though the current usable workaround appears to be lit it happen and ignore the error message.  We should fix it.

**Comment by aviks** [comment]
I believe this is not due to JNI, or indeed any calls we do. This also happens when you attach GDB to a JVM for a regular java program. 

Apparently it is because the JVM does speculative loads (disregard what I said about nulls earlier, sorry)

http://stackoverflow.com/questions/27241575/why-does-java-app-crash-in-gdb-but-runs-normally-in-real-life

**Comment by waTeim** [comment]
A possible workaround/mechanism to test would be to [alter signal use by the JVM](http://www.oracle.com/technetwork/java/javase/signals-139944.html#gbzcj)

**Comment by aviks** [comment]
`-Xrs` or reduced signal handling on the JVM does not have any effect, since SIGSEGV usage is not optional, and is not effected by that flag. 

However, the julia option `--handle-signals=no` removes the segfault message. I have added an FAQ entry for this: http://aviks.github.io/JavaCall.jl/faq.htm
