### ISSUE TITLE
Support for JNI 1.8

### ISSUE THREAD

**Issue by FransM22** [aviks/JavaCall.jl#7]
JavaCall causes an error when using it with JNI versions later than 1.6. The error displayed is `ERROR: assertion failed: jni_version == JNI_VERSION_1_6`. Since JDK 1.8, JNI version 1.8 is included, making this assertion always fail when using JavaCall on *.jar files created with this version of Java.

Line 457 In src/JavaCall.jl (`@assert ccall(jnifunc.GetVersion, Cint, (Ptr{JNIEnv},), penv) == JNI_VERSION_1_6`) causes the error.

Changing the line to `@assert jni_version >= JNI_VERSION_1_6		#Also allowing jni 1.8` solves the issue. I can't find any changes since 1.6, and after a little testing, using JNI 1.8 seems to be working fine.

**Comment by aviks** [comment]
JavaCall.jl now does work on 1.8. The assertion checking for 1.7 has been removed.  In Linux, there are no reported issues due to 1.8. In OSX however, there are some spurious segfaults when moving from 1.7 to 1.8

**Comment by aviks** [comment]
Everything should be fixed in `JavaCall 0.2.3` onwards. Note that on OSX, there are messages printed to console about segfaults, but they are harmless, and are due to the interaction of Java and Julia's signal handlers. In `julia 0.4` run with `--handle-signals=no` (but that might disable `ctrl-C`)

Please let me know if there are any further issues.
